Repository TelloViz/Card-Collection, pull requests merged in 2024-10, with the labels that each got.

#62 Progress report 3
  Documentation/Reports/10_03_24_Progress_Report_3.md
  Documentation/Reports/9_19_24_Progress_Report_2.md
Labels: documentation, devlog

#83 Update ignore
  .gitignore
Labels: bug

#89 Add backend.py for class backend functionality
  CardCollection/backend.py
Labels: enhancement, invalid

#96 Implements all_sets function
  CardCollection/backend.py
Labels: enhancement

#97 Func/requestsetsretrieve
  CardCollection/backendcontroller.py
Labels: enhancement

#100 Func/constructquery
  CardCollection/CardCollection.pyproject
  CardCollection/Tests/test_backend.py
  CardCollection/Tests/testresults.md
  CardCollection/backend.py
Labels: enhancement

#115 Func/queryapi
  CardCollection/backend.py
Labels: improvement

#117 Func/handlesearch
  CardCollection/searchhandler.py
Labels: improvement

#118 Fixed wrong parameter name passed to construct_query
  CardCollection/searchhandler.py
Labels: bug

#123 Created handle_card_process function
  CardCollection/searchhandler.py
Labels: enhancement

#125 Refactor and fix handle_search
  CardCollection/searchhandler.py
Labels: fix

#120 Func/requestsearch
  CardCollection/backendcontroller.py
Labels: enhancement, improvement

#121 Class/cardprocessor
  CardCollection/cardprocessor.py
Labels: enhancement, improvement

#131 UI/frontend
  CardCollection/AbilityInfoBlock.qml
  CardCollection/AttackInfoBlock.qml
  CardCollection/Card3D.qml
  CardCollection/CardCollection.pyproject
  CardCollection/MySearchFilterTools.qml
  CardCollection/MySearchTools.qml
  CardCollection/TypeBlock.qml
  CardCollection/backendcontroller.py
  CardCollection/ball.png
  CardCollection/ballsmall.png
  CardCollection/cardback.png
  CardCollection/cardprocessor.py
  CardCollection/colorlessEnergyCropped.png
  CardCollection/dragonEnergyCropped.png
  CardCollection/main.py
  CardCollection/main.qml
  CardCollection/resource.qrc
  CardCollection/searchhandler.py
Labels: help wanted

#135 Front end/backend fixed
  CardCollection/cardprocessor.py
Labels: fix

#136 Fix/backendcontroller
  CardCollection/CardCollection.pyproject
  CardCollection/FlavorTextBlock.qml
  CardCollection/MySearchFilterTools.qml
  CardCollection/SetLogoBlock.qml
  CardCollection/SetSymbolBlock.qml
  CardCollection/Subtype.qml
  CardCollection/SubtypeBlock.qml
  CardCollection/Type.qml
  CardCollection/TypeBlock.qml
  CardCollection/backendcontroller.py
  CardCollection/cardprocessor.py
  CardCollection/main.qml
  CardCollection/searchhandler.py
Labels: fix
